### ISSUE TITLE
网络环境差时，查看文章详情有时候会崩溃

### ISSUE THREAD

**Issue by Jayin** [EManual/EManual-Client-Java#18]
```console
java.lang.NullPointerException
	at io.github.emanual.java.app.ui.Detail.displayMenu(Detail.java:232)
	at io.github.emanual.java.app.ui.Detail.access$0(Detail.java:231)
	at io.github.emanual.java.app.ui.Detail$1.onFinish(Detail.java:157)
	at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:382)
	at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:135)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:4987)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by Jayin** [comment]
mMenu为null，说明UI(菜单未加载完成)
